### ISSUE TITLE
Crash when leaving to Main Menu

### ISSUE THREAD

**Issue by RaulMarq** [Toeler/Balatro-HandPreview#1]
I had a crash a little over an hour when I left my current run to the Main Menu. I have 8 mods installed, so I'm not entirely sure if the crash was caused by this one specifically or if it's because of mod incompatibilities, but this is the only mod that's mentioned in the portion of the log dedicated to the crash, from what I can tell. I had just unlocked a bunch of stuff for my collection, if that matters at all. [Here's the log in question](https://github.com/user-attachments/files/16168343/lovely-2024.07.10-13.26.06.log).

Just in case, the Steamodded mods I have installed (and activated) are: BalaLib, Deselect All, Hand Preview, Persona Tarot Cards, Simple Anime HD JKQs, Achievements Enabler, Divvy's Preview and Divvy's Simulation.

I'm using Steamodded 1.0.0 Alpha, latest game version on Steam.

**Comment by Toeler** [comment]
Hi @RaulMarq, thanks for the report.

Did you only crash once, or did it continue to crash after reopening the game?

Looking at the log (thanks for providing a log!), it doesn't look related to HandPreview. The reason why HandPreview shows up in that log is that it is wrapping the game's update handler. It doesn't look like it is the cause of the crash. It's possible that it was an actual game crash.

If this occurs again, please reopen the issue and I will try to reproduce the issue.
