### ISSUE TITLE
How to install with Thunderstore mod manager?

### ISSUE THREAD

**Issue by AlejandroAkbal** [Toeler/Balatro-HandPreview#2]
Title says all

**Comment by Toeler** [comment]
Hi @AlejandroAkbal 

The mod is not available on Thunderstore but you can install it manually as long as you are using Steamodded as your mod loader. [Please see the installation instructions here](https://github.com/Toeler/Balatro-HandPreview?tab=readme-ov-file#-installation-instructions).
